### ISSUE TITLE
Throughput testing

### ISSUE THREAD

**Issue by githubmanticore** [nck-2/test-rep#457]
Here's what I suggest to do for throughput testing: 
* [x] Ask Ivinco in channel [#ivinco](https://manticoresearch.slack.com/archives/C7309S5AQ) in Slack to: 
  - sync indexes to sehs01 the same way they do it during pre-release testing (this will give us some part of most of Ivinco's productions indexes) 
  - in addition to that - sync the query logs of the same queries that are used as a basis for pre-release testing. The point is that during pre-release testing they are just being copied from production constantly, but here we just need some amount of recent queries from all the data type we have indexes for 
  - archive that all (or not, it's up to you) 
 * [x] Download the archive/files on `perf3` 
 * [x] Read [my chat](htttps://manticore-community.slack.com/archives/C01FFDRJWFN/p1674747176218769?thread_ts=1674207250.787549&cid=C01FFDRJWFN) with a guy who tried Yandex tank to test Manticore and watch the video below to understand the RPS idea of Yandex tank: it can control not only concurrency (load_type=instances), but RPS (load_type=rps), i.e. it may be just making 500 RPS and it won't care if the server can handle that or not, every 2ms a new request will be issued. 
 * [x] Get familiar with https://github.com/yandex/yandex-tank 
 * [x] Deploy a Manticore instance with the Ivinco's data on `perf`: 
       - extract data from the archive 
       - modify paths to the tables, logs and pidfile if required  
 * [x] Extract actual queries from the query logs 
 * [x] Prepare Yandex Tank config 
 * [x] Run tests 
 * [x] Use https://yandextank.readthedocs.io/en/latest/core_and_modules.html#yandex-overload to visualize the results and make decisions 
   - Watch https://youtu.be/gws7L3EaeC0?t=281 to understand how it works

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
> Download the archive/files on `perf3` 
 
The files are located in `/mnt/ssd/effyis` on `perf3`.

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
During the research and setup process, I discovered that we have a memory leak, which prevented the execution of valid tests for random queries. However, I was able to run a test for a single repeated query with 100 concurrent operations and a rate of 10k requests per second. Here are the results: https://overload.yandex.net/624484 
 
## Instructions for Execution 
 
To run Manticore, use the following command: 
```bash 
cd /mnt/ssd/effyis 
searchd -c manticore-load-test.conf --nodetach 
``` 
 
You can initiate the test as follows: 
```bash 
tank/run 
``` 
 
## Important Information 
 
The script that parses the `query.log` and outputs a ready-to-use list of endpoints for testing is `tank/generate-uris`. Simply execute the command like this: 
```bash 
tank/generate-uris > tank/uris.txt 
``` 
 
The final file, `tank/uris.txt`, is prepared for use but still has a memory leak. Thus, the configuration uses `tank/uris-same.txt`, which contains a single query repeated. 
 
## Yandex Tank Configuration 
 
An editable configuration is available in `tank/load-test.conf`. It contains my token for overload, so tests are automatically uploaded. The current contents are as follows: 
 
```yaml 
phantom: 
  address: 127.0.0.1:13315 
  ssl: false 
  load_profile: 
    load_type: rps # schedule load by defining requests per second 
    schedule: line(1, 10000, 5m) # starting from 1rps growing linearly to 10rps during 10 minutes 
  instances: 100 
  header_http: "1.1" 
  headers: 
    - "[Connection: close]" 
  ammo_type: uri 
  ammofile: /var/loadtest/tank/uris-same.txt 
console: 
  enabled: true 
telegraf: 
  enabled: false 
overload: 
  enabled: true 
  package: yandextank.plugins.DataUploader 
  token_file: /var/loadtest/tank/overload-token.txt 
```
